#!/bin/bash
printf "\n\e[0;32m🍣   Starting elm-live...\e[0m\n\n"
node_modules/.bin/elm-live src/test.elm --open=true --dir=docs --start-page=test.html --port=8002 --path-to-elm=node_modules/.bin/elm -- --output=docs/js/test.js --debug
